# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LAS_MUSIC_009' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LAS_MUSIC_009

  pod 'RealmSwift'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SDWebImage'
  
  pod 'GoogleAPIClientForREST/Drive'
  pod 'GoogleSignIn'
  
  
  pod 'BoxSDK', '~> 5.0'

  pod 'SwiftyDropbox'

  pod 'MSAL'
  pod 'ffmpeg-kit-ios-full', '~> 5.1'
  pod 'UIScrollView-InfiniteScroll', '~> 1.3.0'
  
end
